import type { Video } from "@/types";

// 视频示例数据 - 初音未来官方PV和精选视频
export const videoList: Video[] = [
  {
    id: "video-001",
    title: "初音未来官方PV - 39's SINGING!",
    duration: "4:32",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/videos/miku_official_01.webp",
    video_url: "https://www.youtube.com/watch?v=example1",
    embed_url: "https://www.youtube.com/embed/example1",
    origin_url: "https://www.youtube.com/watch?v=example1",
    origin_site: "YouTube",
    views: 12500000,
    description: "初音未来39特别歌曲官方PV",
    keywords: "初音未来,官方,PV,39",
  },
  {
    id: "video-002",
    title: "World is Mine - 初音未来 MV",
    duration: "4:35",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/videos/miku_mv_01.webp",
    video_url: "https://www.youtube.com/watch?v=example2",
    embed_url: "https://www.youtube.com/embed/example2",
    origin_url: "https://www.youtube.com/watch?v=example2",
    origin_site: "YouTube",
    views: 8200000,
    description: "World is Mine 官方 MV",
    keywords: "World is Mine,初音,MV,supercell",
  },
  {
    id: "video-003",
    title: "初音未来 Magical Mirai 2023 演唱会",
    duration: "1:45:00",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/videos/miku_live_01.webp",
    video_url: "https://www.youtube.com/watch?v=example3",
    embed_url: "https://www.youtube.com/embed/example3",
    origin_url: "https://www.youtube.com/watch?v=example3",
    origin_site: "YouTube",
    views: 5600000,
    description: "Magical Mirai 2023 演唱会精选片段",
    keywords: "初音未来,演唱会,Magical Mirai,Live",
  },
  {
    id: "video-004",
    title: "初音未来 - 甩葱歌 Live",
    duration: "3:15",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/videos/miku_live_02.webp",
    video_url: "https://www.youtube.com/watch?v=example4",
    embed_url: "https://www.youtube.com/embed/example4",
    origin_url: "https://www.youtube.com/watch?v=example4",
    origin_site: "YouTube",
    views: 15000000,
    description: "初音未来经典甩葱歌现场表演",
    keywords: "甩葱歌,初音,Live,经典",
  },
  {
    id: "video-005",
    title: "初音未来「Catch the Wave」Official MV",
    duration: "3:45",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/videos/miku_mv_02.webp",
    video_url: "https://www.youtube.com/watch?v=example5",
    embed_url: "https://www.youtube.com/embed/example5",
    origin_url: "https://www.youtube.com/watch?v=example5",
    origin_site: "YouTube",
    views: 3400000,
    description: "Cruzr×初音未来合作曲官方MV",
    keywords: "Catch the Wave,初音,合作曲,官方",
  },
  {
    id: "video-006",
    title: "初音未来「老虎raser」动画PV",
    duration: "3:20",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/videos/miku_pv_01.webp",
    video_url: "https://www.youtube.com/watch?v=example6",
    embed_url: "https://www.youtube.com/embed/example6",
    origin_url: "https://www.youtube.com/watch?v=example6",
    origin_site: "YouTube",
    views: 4800000,
    description: "初音未来老虎raser动画PV",
    keywords: "老虎raser,初音,动画PV,摇滚",
  },
  {
    id: "video-007",
    title: "初音未来「 Blessing Waltz 」Official MV",
    duration: "4:10",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/videos/miku_mv_03.webp",
    video_url: "https://www.youtube.com/watch?v=example7",
    embed_url: "https://www.youtube.com/embed/example7",
    origin_url: "https://www.youtube.com/watch?v=example7",
    origin_site: "YouTube",
    views: 2100000,
    description: "初音未来 Blessing Waltz 官方MV",
    keywords: "Blessing Waltz,初音,官方,圆舞曲",
  },
  {
    id: "video-008",
    title: "初音未来「月西江」Live Stage",
    duration: "4:28",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/videos/miku_live_03.webp",
    video_url: "https://www.youtube.com/watch?v=example8",
    embed_url: "https://www.youtube.com/embed/example8",
    origin_url: "https://www.youtube.com/watch?v=example8",
    origin_site: "YouTube",
    views: 6800000,
    description: "月西江 Live Stage 精彩片段",
    keywords: "月西江,初音,Live,舞台",
  },
];
