import type { Video } from "@/types";

// 初音未来精选视频 - 全部为真实的官方 MV / 官方 PV / Live 数字版
// 来源平台:YouTube(官方创作者频道 / 初音未来官方频道)
// thumb_url 使用 YouTube 官方封面 https://i.ytimg.com/vi/<id>/hqdefault.jpg
export const videoList: Video[] = [
  {
    id: "video-001",
    title: "World is Mine - ryo (supercell) feat. 初音ミク",
    duration: "4:09",
    thumb_url: "https://i.ytimg.com/vi/jhl5afLEKdo/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=jhl5afLEKdo",
    embed_url: "https://www.youtube.com/embed/jhl5afLEKdo",
    origin_url: "https://www.youtube.com/watch?v=jhl5afLEKdo",
    origin_site: "YouTube",
    views: 23000000,
    upload_date: "2010-08-09",
    description: "supercell 的 ryo 创作的初音未来代表作之一,初音未来官方频道发布。",
    keywords: "World is Mine,初音ミク,supercell,ryo,MV",
  },
  {
    id: "video-002",
    title: "Tell Your World - livetune feat. 初音ミク",
    duration: "4:11",
    thumb_url: "https://i.ytimg.com/vi/PqJNc9KVIZE/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=PqJNc9KVIZE",
    embed_url: "https://www.youtube.com/embed/PqJNc9KVIZE",
    origin_url: "https://www.youtube.com/watch?v=PqJNc9KVIZE",
    origin_site: "YouTube",
    views: 27000000,
    upload_date: "2012-03-14",
    description: "kz(livetune)创作的经典曲目官方 Music Video,曾用于 Google Chrome 广告。",
    keywords: "Tell Your World,livetune,kz,初音ミク,MV",
  },
  {
    id: "video-003",
    title: "砂の惑星 (DUNE) - ハチ feat. 初音ミク",
    duration: "3:43",
    thumb_url: "https://i.ytimg.com/vi/AS4q9yaWJkI/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=AS4q9yaWJkI",
    embed_url: "https://www.youtube.com/embed/AS4q9yaWJkI",
    origin_url: "https://www.youtube.com/watch?v=AS4q9yaWJkI",
    origin_site: "YouTube",
    views: 45000000,
    upload_date: "2017-07-15",
    description: "米津玄师(ハチ)为 Magical Mirai 2017 创作的主题曲官方 MV。",
    keywords: "砂の惑星,DUNE,ハチ,米津玄师,初音ミク",
  },
  {
    id: "video-004",
    title: "ロミオとシンデレラ - doriko feat. 初音ミク【official MV】",
    duration: "4:24",
    thumb_url: "https://i.ytimg.com/vi/9HrOqmiEsN8/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=9HrOqmiEsN8",
    embed_url: "https://www.youtube.com/embed/9HrOqmiEsN8",
    origin_url: "https://www.youtube.com/watch?v=9HrOqmiEsN8",
    origin_site: "YouTube",
    views: 13000000,
    upload_date: "2019-08-30",
    description: "doriko 经典曲目「罗密欧与灰姑娘」官方 MV。",
    keywords: "ロミオとシンデレラ,Romeo and Cinderella,doriko,初音ミク,MV",
  },
  {
    id: "video-005",
    title: "アンノウン・マザーグース (Unknown Mother-Goose) - wowaka feat. 初音ミク",
    duration: "4:08",
    thumb_url: "https://i.ytimg.com/vi/P_CSdxSGfaA/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=P_CSdxSGfaA",
    embed_url: "https://www.youtube.com/embed/P_CSdxSGfaA",
    origin_url: "https://www.youtube.com/watch?v=P_CSdxSGfaA",
    origin_site: "YouTube",
    views: 28000000,
    upload_date: "2017-08-31",
    description: "wowaka 时隔多年回归 VOCALOID 的官方作品。",
    keywords: "アンノウン・マザーグース,Unknown Mother-Goose,wowaka,初音ミク,Official",
  },
  {
    id: "video-006",
    title: "ローリンガール (Rollin' Girl) - wowaka feat. 初音ミク",
    duration: "3:32",
    thumb_url: "https://i.ytimg.com/vi/vnw8zURAxkU/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=vnw8zURAxkU",
    embed_url: "https://www.youtube.com/embed/vnw8zURAxkU",
    origin_url: "https://www.youtube.com/watch?v=vnw8zURAxkU",
    origin_site: "YouTube",
    views: 21000000,
    upload_date: "2017-09-02",
    description: "wowaka 殿堂级名曲「Rollin' Girl」官方上传版本。",
    keywords: "ローリンガール,Rollin Girl,wowaka,初音ミク,Official",
  },
  {
    id: "video-007",
    title: "ヴァンパイア (Vampire) - DECO*27 feat. 初音ミク",
    duration: "2:51",
    thumb_url: "https://i.ytimg.com/vi/e1xCOsgWG0M/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=e1xCOsgWG0M",
    embed_url: "https://www.youtube.com/embed/e1xCOsgWG0M",
    origin_url: "https://www.youtube.com/watch?v=e1xCOsgWG0M",
    origin_site: "YouTube",
    views: 80000000,
    upload_date: "2021-04-21",
    description: "DECO*27 现象级热门曲目「Vampire」官方 MV。",
    keywords: "ヴァンパイア,Vampire,DECO*27,初音ミク,MV",
  },
  {
    id: "video-008",
    title: "ラビットホール (Rabbit Hole) - DECO*27 feat. 初音ミク",
    duration: "2:59",
    thumb_url: "https://i.ytimg.com/vi/eSW2LVbPThw/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=eSW2LVbPThw",
    embed_url: "https://www.youtube.com/embed/eSW2LVbPThw",
    origin_url: "https://www.youtube.com/watch?v=eSW2LVbPThw",
    origin_site: "YouTube",
    views: 120000000,
    upload_date: "2023-05-20",
    description: "DECO*27 创作、兔女郎造型初音的官方 MV,YouTube 破亿播放。",
    keywords: "ラビットホール,Rabbit Hole,DECO*27,初音ミク,MV",
  },
  {
    id: "video-009",
    title: "モザイクロール (Reloaded) - DECO*27 feat. 初音ミク",
    duration: "3:30",
    thumb_url: "https://i.ytimg.com/vi/WysuxO4yR04/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=WysuxO4yR04",
    embed_url: "https://www.youtube.com/embed/WysuxO4yR04",
    origin_url: "https://www.youtube.com/watch?v=WysuxO4yR04",
    origin_site: "YouTube",
    views: 40000000,
    upload_date: "2020-09-23",
    description: "DECO*27 经典曲「马赛克卷」重制版官方 MV。",
    keywords: "モザイクロール,Mozaik Role,DECO*27,初音ミク,Reloaded",
  },
  {
    id: "video-010",
    title: "ヒバナ -Reloaded- / Leo/need × 初音ミク (プロセカ 3DMV)",
    duration: "3:36",
    thumb_url: "https://i.ytimg.com/vi/i16qWEUjd4o/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=i16qWEUjd4o",
    embed_url: "https://www.youtube.com/embed/i16qWEUjd4o",
    origin_url: "https://www.youtube.com/watch?v=i16qWEUjd4o",
    origin_site: "YouTube",
    views: 18000000,
    upload_date: "2021-03-30",
    description: "《Project SEKAI 彩色舞台》官方频道发布的「Hibana -Reloaded-」3DMV。",
    keywords: "ヒバナ,Hibana,DECO*27,プロセカ,Project SEKAI,3DMV",
  },
  {
    id: "video-011",
    title: "FREELY TOMORROW - Mitchie M feat. 初音ミク【公式PV】",
    duration: "3:54",
    thumb_url: "https://i.ytimg.com/vi/KmvydnVTriE/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=KmvydnVTriE",
    embed_url: "https://www.youtube.com/embed/KmvydnVTriE",
    origin_url: "https://www.youtube.com/watch?v=KmvydnVTriE",
    origin_site: "YouTube",
    views: 12000000,
    upload_date: "2011-08-31",
    description: "Mitchie M 以拟人化调教闻名的代表曲官方 PV。",
    keywords: "FREELY TOMORROW,Mitchie M,初音ミク,公式PV",
  },
  {
    id: "video-012",
    title: "アゲアゲアゲイン (Ageage Again) - Mitchie M feat. 初音ミク フルver.PV",
    duration: "3:54",
    thumb_url: "https://i.ytimg.com/vi/uwwU55zBYlQ/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=uwwU55zBYlQ",
    embed_url: "https://www.youtube.com/embed/uwwU55zBYlQ",
    origin_url: "https://www.youtube.com/watch?v=uwwU55zBYlQ",
    origin_site: "YouTube",
    views: 6000000,
    upload_date: "2013-11-28",
    description: "《初音ミク Project mirai 2》主题曲官方完整版 PV。",
    keywords: "アゲアゲアゲイン,Ageage Again,Mitchie M,初音ミク,Project mirai",
  },
  {
    id: "video-013",
    title: "ありふれたせかいせいふく (Common World Domination) - ピノキオピー feat. 初音ミク",
    duration: "3:39",
    thumb_url: "https://i.ytimg.com/vi/8Z3TbMBfDM0/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=8Z3TbMBfDM0",
    embed_url: "https://www.youtube.com/embed/8Z3TbMBfDM0",
    origin_url: "https://www.youtube.com/watch?v=8Z3TbMBfDM0",
    origin_site: "YouTube",
    views: 16000000,
    upload_date: "2016-08-31",
    description: "PinocchioP 官方频道发布的「平凡的世界征服」MV。",
    keywords: "ありふれたせかいせいふく,Common World Domination,ピノキオピー,PinocchioP,初音ミク",
  },
  {
    id: "video-014",
    title: "神っぽいな (God-ish) - ピノキオピー feat. 初音ミク",
    duration: "3:25",
    thumb_url: "https://i.ytimg.com/vi/EHBFKhLUVig/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=EHBFKhLUVig",
    embed_url: "https://www.youtube.com/embed/EHBFKhLUVig",
    origin_url: "https://www.youtube.com/watch?v=EHBFKhLUVig",
    origin_site: "YouTube",
    views: 60000000,
    upload_date: "2021-08-25",
    description: "PinocchioP 现象级热门曲「God-ish」官方 MV。",
    keywords: "神っぽいな,God-ish,ピノキオピー,PinocchioP,初音ミク",
  },
  {
    id: "video-015",
    title: "不死身ごっこ (Playing Immortal) - ピノキオピー feat. 初音ミク",
    duration: "3:41",
    thumb_url: "https://i.ytimg.com/vi/hCc0iI8jdQU/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=hCc0iI8jdQU",
    embed_url: "https://www.youtube.com/embed/hCc0iI8jdQU",
    origin_url: "https://www.youtube.com/watch?v=hCc0iI8jdQU",
    origin_site: "YouTube",
    views: 11000000,
    upload_date: "2022-09-21",
    description: "PinocchioP 官方频道发布的「Playing Immortal」MV。",
    keywords: "不死身ごっこ,Playing Immortal,ピノキオピー,PinocchioP,初音ミク",
  },
  {
    id: "video-016",
    title: "愛属性 (Love Attribute) - ピノキオピー feat. 初音ミク",
    duration: "3:55",
    thumb_url: "https://i.ytimg.com/vi/Xx1TnVObQ0k/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=Xx1TnVObQ0k",
    embed_url: "https://www.youtube.com/embed/Xx1TnVObQ0k",
    origin_url: "https://www.youtube.com/watch?v=Xx1TnVObQ0k",
    origin_site: "YouTube",
    views: 8000000,
    upload_date: "2023-08-30",
    description: "PinocchioP 官方频道发布的「Love Attribute」MV。",
    keywords: "愛属性,Love Attribute,ピノキオピー,PinocchioP,初音ミク",
  },
  {
    id: "video-017",
    title: "恋の恋による恋のための恋 (Love for Love by Love of Love) - ピノキオピー feat. 初音ミク",
    duration: "3:33",
    thumb_url: "https://i.ytimg.com/vi/QvO8kcWFFT0/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=QvO8kcWFFT0",
    embed_url: "https://www.youtube.com/embed/QvO8kcWFFT0",
    origin_url: "https://www.youtube.com/watch?v=QvO8kcWFFT0",
    origin_site: "YouTube",
    views: 7000000,
    upload_date: "2020-08-31",
    description: "PinocchioP 官方频道发布的恋爱主题 MV。",
    keywords: "恋の恋による恋のための恋,ピノキオピー,PinocchioP,初音ミク,MV",
  },
  {
    id: "video-018",
    title: "僕なんかいなくても (With or Without Me) - ピノキオピー feat. 初音ミク",
    duration: "4:30",
    thumb_url: "https://i.ytimg.com/vi/A1XqqVWyUl4/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=A1XqqVWyUl4",
    embed_url: "https://www.youtube.com/embed/A1XqqVWyUl4",
    origin_url: "https://www.youtube.com/watch?v=A1XqqVWyUl4",
    origin_site: "YouTube",
    views: 9000000,
    upload_date: "2019-12-28",
    description: "PinocchioP 官方频道发布的「With or Without Me」MV。",
    keywords: "僕なんかいなくても,With or Without Me,ピノキオピー,PinocchioP,初音ミク",
  },
  {
    id: "video-019",
    title: "歌姫失格 (Rejected Diva) - ピノキオピー feat. 初音ミク",
    duration: "4:16",
    thumb_url: "https://i.ytimg.com/vi/adE8jVLoLPo/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=adE8jVLoLPo",
    embed_url: "https://www.youtube.com/embed/adE8jVLoLPo",
    origin_url: "https://www.youtube.com/watch?v=adE8jVLoLPo",
    origin_site: "YouTube",
    views: 14000000,
    upload_date: "2023-12-27",
    description: "PinocchioP 官方频道发布的「Rejected Diva」MV。",
    keywords: "歌姫失格,Rejected Diva,ピノキオピー,PinocchioP,初音ミク",
  },
  {
    id: "video-020",
    title: "超主人公 (Super Superhero) - ピノキオピー feat. 初音ミク",
    duration: "3:39",
    thumb_url: "https://i.ytimg.com/vi/thmR2SmkeDU/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=thmR2SmkeDU",
    embed_url: "https://www.youtube.com/embed/thmR2SmkeDU",
    origin_url: "https://www.youtube.com/watch?v=thmR2SmkeDU",
    origin_site: "YouTube",
    views: 13000000,
    upload_date: "2022-12-25",
    description: "PinocchioP 官方频道发布的「Super Superhero」MV。",
    keywords: "超主人公,Super Superhero,ピノキオピー,PinocchioP,初音ミク",
  },
  {
    id: "video-021",
    title: "ユーチューバー (UTuber) - ピノキオピー feat. 初音ミク",
    duration: "3:45",
    thumb_url: "https://i.ytimg.com/vi/lTUVw7wd5qY/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=lTUVw7wd5qY",
    embed_url: "https://www.youtube.com/embed/lTUVw7wd5qY",
    origin_url: "https://www.youtube.com/watch?v=lTUVw7wd5qY",
    origin_site: "YouTube",
    views: 10000000,
    upload_date: "2018-08-31",
    description: "PinocchioP 官方频道发布的「UTuber」MV。",
    keywords: "ユーチューバー,UTuber,ピノキオピー,PinocchioP,初音ミク",
  },
  {
    id: "video-022",
    title: "ポケットのモンスター (The Pokémon Inside My Heart) - ピノキオピー feat. 初音ミク",
    duration: "3:52",
    thumb_url: "https://i.ytimg.com/vi/lIoi2r3f5fU/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=lIoi2r3f5fU",
    embed_url: "https://www.youtube.com/embed/lIoi2r3f5fU",
    origin_url: "https://www.youtube.com/watch?v=lIoi2r3f5fU",
    origin_site: "YouTube",
    views: 8500000,
    upload_date: "2025-02-12",
    description: "PinocchioP 与 Pokémon 联动的官方 MV。",
    keywords: "ポケットのモンスター,Pokemon,ピノキオピー,PinocchioP,初音ミク",
  },
  {
    id: "video-023",
    title: "初音ミク「マジカルミライ」10th Anniversary ダイジェスト (Live)",
    duration: "3:30",
    thumb_url: "https://i.ytimg.com/vi/HmEZHjOCETA/hqdefault.jpg",
    video_url: "https://www.youtube.com/watch?v=HmEZHjOCETA",
    embed_url: "https://www.youtube.com/embed/HmEZHjOCETA",
    origin_url: "https://www.youtube.com/watch?v=HmEZHjOCETA",
    origin_site: "YouTube",
    views: 2000000,
    upload_date: "2022-12-09",
    description: "初音未来官方频道发布的 Magical Mirai 十周年演唱会精华影像。",
    keywords: "Magical Mirai,マジカルミライ,10th Anniversary,演唱会,Live,初音ミク",
  },
];
