import type { ExternalSite } from "@/types";

// 初音未来相关视频/音声投稿平台数据
export const videoSites: ExternalSite[] = [
  {
    id: "site-001",
    title: "ニコニコ動画「初音ミク」タグ",
    description: "日本最大の動画投稿サイト。VOCALOID 文化の発祥地であり、「初音ミク」タグには膨大な投稿作品が集まっています。",
    url: "https://www.nicovideo.jp/tag/%E5%88%9D%E9%9F%B3%E3%83%9F%E3%82%AF",
    favicon: "https://www.google.com/s2/favicons?domain=nicovideo.jp&sz=64",
    category: "投稿平台",
  },
  {
    id: "site-002",
    title: "ニコニコ動画 VOCALOID ランキング",
    description: "ニコニコ動画の VOCALOID ジャンル別ランキング。最新の人気ボカロ曲・初音ミク楽曲をチェックできます。",
    url: "https://www.nicovideo.jp/ranking/genre/all?tag=VOCALOID",
    favicon: "https://www.google.com/s2/favicons?domain=nicovideo.jp&sz=64",
    category: "投稿平台",
  },
  {
    id: "site-003",
    title: "YouTube「初音ミク」検索",
    description: "全球最大の動画プラットフォーム。世界中のクリエイターが初音ミクの楽曲・MV・ライブ映像を投稿しています。",
    url: "https://www.youtube.com/results?search_query=%E5%88%9D%E9%9F%B3%E3%83%9F%E3%82%AF",
    favicon: "https://www.google.com/s2/favicons?domain=youtube.com&sz=64",
    category: "视频",
  },
  {
    id: "site-004",
    title: "初音ミク 公式 YouTube チャンネル",
    description: "クリプトン・フューチャー・メディア運営の初音ミク公式チャンネル。マジカルミライ映像や公式 PV を配信。",
    url: "https://www.youtube.com/@HatsuneMiku",
    favicon: "https://www.google.com/s2/favicons?domain=youtube.com&sz=64",
    category: "视频",
  },
  {
    id: "site-005",
    title: "bilibili 初音未来搜索",
    description: "国内最大的 ACGN 内容平台，汇集大量初音未来的视频投稿、二次创作与弹幕互动。",
    url: "https://search.bilibili.com/all?keyword=%E5%88%9D%E9%9F%B3%E6%9C%AA%E6%9D%A5",
    favicon: "https://www.google.com/s2/favicons?domain=bilibili.com&sz=64",
    category: "视频",
  },
  {
    id: "site-006",
    title: "bilibili VOCALOID·UTAU 分区",
    description: "bilibili 音乐区下的 VOCALOID·UTAU 子分区，是国内 P 主投稿初音原创与翻调作品的主要阵地。",
    url: "https://www.bilibili.com/v/music/vocaloid",
    favicon: "https://www.google.com/s2/favicons?domain=bilibili.com&sz=64",
    category: "视频",
  },
  {
    id: "site-007",
    title: "piapro（ピアプロ）",
    description: "クリプトン公式のクリエイター投稿コミュニティ。初音ミクの楽曲・イラスト・歌詞などの素材を投稿・共有できます。",
    url: "https://piapro.jp/",
    favicon: "https://www.google.com/s2/favicons?domain=piapro.jp&sz=64",
    category: "投稿平台",
  },
  {
    id: "site-008",
    title: "ニコニコ静画",
    description: "ニコニコの静止画・イラスト投稿サービス。初音ミクの同人イラストやマンガ作品を数多く閲覧できます。",
    url: "https://seiga.nicovideo.jp/",
    favicon: "https://www.google.com/s2/favicons?domain=seiga.nicovideo.jp&sz=64",
    category: "投稿平台",
  },
  {
    id: "site-009",
    title: "ニコニ・コモンズ",
    description: "ニコニコの二次創作素材共有サイト。初音ミク関連の音源・画像・動画素材を投稿・利用できます。",
    url: "https://commons.nicovideo.jp/",
    favicon: "https://www.google.com/s2/favicons?domain=commons.nicovideo.jp&sz=64",
    category: "投稿平台",
  },
  {
    id: "site-010",
    title: "SoundCloud #hatsunemiku",
    description: "世界的な音声・楽曲投稿プラットフォーム。hatsunemiku タグから海外クリエイターのボカロ楽曲を試聴できます。",
    url: "https://soundcloud.com/tags/hatsunemiku",
    favicon: "https://www.google.com/s2/favicons?domain=soundcloud.com&sz=64",
    category: "音声",
  },
  {
    id: "site-011",
    title: "Bandcamp Hatsune Miku",
    description: "インディーアーティスト向けの音楽配信・販売プラットフォーム。初音ミクを使ったアルバムを購入・試聴できます。",
    url: "https://bandcamp.com/search?q=hatsune%20miku",
    favicon: "https://www.google.com/s2/favicons?domain=bandcamp.com&sz=64",
    category: "音声",
  },
  {
    id: "site-012",
    title: "Spotify 初音ミク",
    description: "世界最大級の音楽ストリーミングサービス。初音ミク楽曲のプレイリストやアーティストページを楽しめます。",
    url: "https://open.spotify.com/search/hatsune%20miku",
    favicon: "https://www.google.com/s2/favicons?domain=spotify.com&sz=64",
    category: "音声",
  },
  {
    id: "site-013",
    title: "Apple Music 初音ミク",
    description: "Apple の音楽ストリーミングサービス。初音ミクの公式アルバムや人気曲を高音質で配信しています。",
    url: "https://music.apple.com/us/search?term=hatsune%20miku",
    favicon: "https://www.google.com/s2/favicons?domain=music.apple.com&sz=64",
    category: "音声",
  },
  {
    id: "site-014",
    title: "Vimeo",
    description: "クリエイター志向の高画質動画プラットフォーム。初音ミクの MV やライブ映像を投稿するアーティストもいます。",
    url: "https://vimeo.com/",
    favicon: "https://www.google.com/s2/favicons?domain=vimeo.com&sz=64",
    category: "视频",
  },
  {
    id: "site-015",
    title: "Pixiv「初音ミク」タグ",
    description: "日本最大級のイラスト投稿コミュニティ。初音ミクの同人イラストや漫画作品を「初音ミク」タグから閲覧できます。",
    url: "https://www.pixiv.net/tags/%E5%88%9D%E9%9F%B3%E3%83%9F%E3%82%AF",
    favicon: "https://www.google.com/s2/favicons?domain=pixiv.net&sz=64",
    category: "投稿平台",
  },
  {
    id: "site-016",
    title: "VocaDB",
    description: "全球范围的 VOCALOID 楽曲データベース。曲師・歌手・アルバム別に初音ミク楽曲を検索・閲覧できます。",
    url: "https://vocadb.net/",
    favicon: "https://www.google.com/s2/favicons?domain=vocadb.net&sz=64",
    category: "数据库",
  },
  {
    id: "site-017",
    title: "TikTok #hatsunemiku",
    description: "ショート動画プラットフォーム。hatsunemiku ハッシュタグで初音ミクのダンス・楽曲・二次創作が拡散しています。",
    url: "https://www.tiktok.com/tag/hatsunemiku",
    favicon: "https://www.google.com/s2/favicons?domain=tiktok.com&sz=64",
    category: "视频",
  },
  {
    id: "site-018",
    title: "マジカルミライ 公式サイト",
    description: "クリプトン主催の初音ミク公式ライブ＆企画展「マジカルミライ」。公募楽曲やライブ映像情報を発信しています。",
    url: "https://magicalmirai.com/",
    favicon: "https://www.google.com/s2/favicons?domain=magicalmirai.com&sz=64",
    category: "投稿平台",
  },
];
