import type { ExternalSite } from "@/types";

// 初音未来相关投稿网站数据
export const videoSites: ExternalSite[] = [
  {
    id: "site-001",
    title: "Niconico Douga",
    description: "日本最大的视频投稿网站，初音未来的诞生地。VOCALOID 文化发源地，拥有海量初音创作内容。",
    url: "https://www.nicovideo.jp/",
    favicon: "https://www.nicovideo.jp/favicon.ico",
    category: "日本",
    image: "https://cdn.jsdelivr.net/gh/0326/imgs@main/sites/niconico.webp",
  },
  {
    id: "site-002",
    title: "YouTube",
    description: "全球最大的视频平台，众多初音创作者在此发布作品，官方频道也在此运营。",
    url: "https://www.youtube.com/results?search_query=%E5%88%9D%E9%9F%B3%E6%9C%AA%E6%9D%A5",
    favicon: "https://www.youtube.com/s/desktop/favicon.ico",
    category: "全球",
    image: "https://cdn.jsdelivr.net/gh/0326/imgs@main/sites/youtube.webp",
  },
  {
    id: "site-003",
    title: "Vocaloid",
    description: "VOCALOID 官方网站，提供最新资讯、官方音乐下载和初音未来相关信息。",
    url: "https://ec.cygames.jp/shop/?utm_source=google&utm_medium=cpc&utm_campaign=general&gad_source=1&gclid=example",
    favicon: "https://piapro.net/favicon.ico",
    category: "官方",
    image: "https://cdn.jsdelivr.net/gh/0326/imgs@main/sites/piapro.webp",
  },
  {
    id: "site-004",
    title: "初音未来官网",
    description: "初音未来官方网站，提供最新活动资讯、周边信息和粉丝俱乐部入口。",
    url: "https:// HatsuneMikuOfficial.com",
    favicon: "",
    category: "官方",
    image: "https://cdn.jsdelivr.net/gh/0326/imgs@main/sites/miku_official.webp",
  },
  {
    id: "site-005",
    title: "VocaDB",
    description: "VOCALOID 音乐数据库，收录全球范围内的 VOCALOID 歌曲，可按曲师、歌手、专辑浏览。",
    url: "https://vocadb.net/",
    favicon: "https://vocadb.net/favicon.ico",
    category: "数据库",
    image: "https://cdn.jsdelivr.net/gh/0326/imgs@main/sites/vocadb.webp",
  },
  {
    id: "site-006",
    title: "Vocarock",
    description: "专注于摇滚风格 VOCALOID 音乐的网站，汇集众多硬核摇滚初音曲目。",
    url: "https://vocarock.com/",
    favicon: "https://vocarock.com/favicon.ico",
    category: "音乐",
    image: "https://cdn.jsdelivr.net/gh/0326/imgs@main/sites/vocarock.webp",
  },
  {
    id: "site-007",
    title: "初音ミク append",
    description: "初音 Append 专用曲库，收录使用初音 Append 音源创作的优质音乐作品。",
    url: "https:// AppendMiku.com/",
    favicon: "",
    category: "音源",
    image: "https://cdn.jsdelivr.net/gh/0326/imgs@main/sites/append.webp",
  },
  {
    id: "site-008",
    title: "Pixiv",
    description: "日本知名插画社区，许多初音未来同人创作者在此发布插画作品。",
    url: "https://www.pixiv.net/tags/%E5%88%9D%E9%9F%B3%E6%9C%AA%E6%9D%A5/works",
    favicon: "https://www.pixiv.net/favicon.ico",
    category: "日本",
    image: "https://cdn.jsdelivr.net/gh/0326/imgs@main/sites/pixiv.webp",
  },
  {
    id: "site-009",
    title: "Niconico Seiga",
    description: "Niconico 的漫画/插画投稿平台，可浏览初音相关同人插画作品。",
    url: "https://seiga.nicovideo.jp/",
    favicon: "https://seiga.nicovideo.jp/favicon.ico",
    category: "日本",
    image: "https://cdn.jsdelivr.net/gh/0326/imgs@main/sites/seiga.webp",
  },
  {
    id: "site-010",
    title: "Bilibili",
    description: "国内最大的 ACGN 内容平台，拥有大量初音未来相关的视频、弹幕和二次创作内容。",
    url: "https://search.bilibili.com/search?keyword=%E5%88%9D%E9%9F%B3%E6%9C%AA%E6%9D%A5",
    favicon: "https://www.bilibili.com/favicon.ico",
    category: "国内",
    image: "https://cdn.jsdelivr.net/gh/0326/imgs@main/sites/bilibili.webp",
  },
];
