import type { Avatar } from "@/types";

// 头像示例数据 - 使用初音未来相关的公开图片
export const avatars: Avatar[] = [
  {
    id: "avatar-001",
    title: "初音未来 - 蓝色双马尾",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_blue_01.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_blue_01.webp",
    origin_site: "https://pixiv.net",
    keywords: "初音未来,VOCALOID,蓝色双马尾,二次元头像",
    description: "经典初音未来蓝色双马尾形象头像",
  },
  {
    id: "avatar-002",
    title: "初音未来 - 粉色可爱",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_pink_01.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_pink_01.webp",
    origin_site: "https://pixiv.net",
    keywords: "初音未来,VOCALOID,粉色,可爱头像",
    description: "粉色系初音未来可爱风格头像",
  },
  {
    id: "avatar-003",
    title: "初音未来 - 冰雪女王",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_ice_01.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_ice_01.webp",
    origin_site: "https://pixiv.net",
    keywords: "初音未来,冰雪,冬季主题,唯美头像",
    description: "冰雪主题初音未来唯美头像",
  },
  {
    id: "avatar-004",
    title: "初音未来 - 樱花季",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_sakura_01.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_sakura_01.webp",
    origin_site: "https://pixiv.net",
    keywords: "初音未来,樱花,春季,浪漫头像",
    description: "樱花季主题初音头像",
  },
  {
    id: "avatar-005",
    title: "初音未来 - 电子舞曲",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_edm_01.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_edm_01.webp",
    origin_site: "https://pixiv.net",
    keywords: "初音未来,电子音乐,EDM,VOCALOID头像",
    description: "电子音乐主题初音未来头像",
  },
  {
    id: "avatar-006",
    title: "初音未来 - 魔法少女",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_magic_01.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_magic_01.webp",
    origin_site: "https://pixiv.net",
    keywords: "初音未来,魔法少女,可爱,变身头像",
    description: "魔法少女风格初音头像",
  },
  {
    id: "avatar-007",
    title: "初音未来 - 赛博朋克",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_cyber_01.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_cyber_01.webp",
    origin_site: "https://pixiv.net",
    keywords: "初音未来,赛博朋克,未来感,科技头像",
    description: "赛博朋克风格初音头像",
  },
  {
    id: "avatar-008",
    title: "初音未来 - 校园风",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_school_01.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_school_01.webp",
    origin_site: "https://pixiv.net",
    keywords: "初音未来,校园,制服,学生头像",
    description: "校园风格初音未来头像",
  },
  {
    id: "avatar-009",
    title: "初音未来 - 和服",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_kimono_01.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_kimono_01.webp",
    origin_site: "https://pixiv.net",
    keywords: "初音未来,和服,日式,传统头像",
    description: "和服主题初音头像",
  },
  {
    id: "avatar-010",
    title: "初音未来 - 万圣节",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_halloween_01.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_halloween_01.webp",
    origin_site: "https://pixiv.net",
    keywords: "初音未来,万圣节,南瓜,节日头像",
    description: "万圣节主题初音头像",
  },
  {
    id: "avatar-011",
    title: "初音未来 - 圣诞节",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_christmas_01.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_christmas_01.webp",
    origin_site: "https://pixiv.net",
    keywords: "初音未来,圣诞节,圣诞树,节日头像",
    description: "圣诞节主题初音头像",
  },
  {
    id: "avatar-012",
    title: "初音未来 - 婚纱",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_wedding_01.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/avatars/miku_wedding_01.webp",
    origin_site: "https://pixiv.net",
    keywords: "初音未来,婚纱,礼服,唯美头像",
    description: "婚纱礼服主题初音头像",
  },
];
