import type { Avatar } from "@/types";

// 初音未来头像数据 - 图源: mikuworldonline/img@main (jsdelivr CDN), 原始来源 3gbizhi.com
// 采用竖版/方形构图壁纸作为头像缩略, 全部 thumb_url 已 curl 实测返回 200
export const avatars: Avatar[] = [
  {
    id: "avatar-001",
    title: "初音未来 · 日落霞光蓝发",
    thumb_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/e9512bfdf025ec4b.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/e9512bfdf025ec4b.webp",
    origin_site: "https://www.3gbizhi.com/wallDM/6121.html",
    keywords: "初音未来,VOCALOID,蓝色长发,霞光,二次元头像",
    description: "蓝色长发初音在日落霞光中的唯美动漫头像",
    is_circle: true,
  },
  {
    id: "avatar-002",
    title: "初音未来 · 赛博朋克少女",
    thumb_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/e0cb978091e4ad6e.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/e0cb978091e4ad6e.webp",
    origin_site: "https://www.3gbizhi.com/wallDM/678.html",
    keywords: "初音未来,VOCALOID,赛博朋克,少女,二次元头像",
    description: "赛博朋克风格的初音未来动漫少女头像",
    is_circle: false,
  },
  {
    id: "avatar-003",
    title: "初音未来 · 蓝发双马尾",
    thumb_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/d3aa2bdb73069faa.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/d3aa2bdb73069faa.webp",
    origin_site: "https://www.3gbizhi.com/wallDM/5541.html",
    keywords: "初音未来,VOCALOID,蓝发,双马尾,二次元头像",
    description: "经典蓝发双马尾初音未来人物头像",
    is_circle: true,
  },
  {
    id: "avatar-004",
    title: "初音未来 · 逆光水中",
    thumb_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/3bd14b92403ec354.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/3bd14b92403ec354.webp",
    origin_site: "https://www.3gbizhi.com/wallDM/5307.html",
    keywords: "初音未来,VOCALOID,逆光,水中,唯美,二次元头像",
    description: "逆光中沉入水里的初音未来唯美头像",
    is_circle: false,
  },
  {
    id: "avatar-005",
    title: "初音未来 · 花园小清新",
    thumb_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/df9c88b030439d35.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/df9c88b030439d35.webp",
    origin_site: "https://www.3gbizhi.com/wallDM/5250.html",
    keywords: "初音未来,VOCALOID,花园,白裙,小清新,二次元头像",
    description: "坐在花园草地上的小清新白裙初音头像",
    is_circle: true,
  },
  {
    id: "avatar-006",
    title: "初音未来 · 朋克双马尾",
    thumb_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/ed1d73a8dee7bdd3.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/ed1d73a8dee7bdd3.webp",
    origin_site: "https://www.3gbizhi.com/wallDM/5012.html",
    keywords: "初音未来,VOCALOID,双马尾,朋克,手绘,二次元头像",
    description: "双马尾朋克风初音未来手绘插画头像",
    is_circle: false,
  },
  {
    id: "avatar-007",
    title: "初音未来 · 绿色系",
    thumb_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/50daaebc614372e0.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/50daaebc614372e0.webp",
    origin_site: "https://www.3gbizhi.com/wallDM/2687.html",
    keywords: "初音未来,VOCALOID,绿色系,二次元头像",
    description: "绿色系配色的初音未来主题头像",
    is_circle: true,
  },
  {
    id: "avatar-008",
    title: "初音未来 · 萌系动漫",
    thumb_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/c01b3a958ef48af9.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/c01b3a958ef48af9.webp",
    origin_site: "https://www.3gbizhi.com/wallDM/3057.html",
    keywords: "初音未来,VOCALOID,萌系,动漫,二次元头像",
    description: "萌系动漫风格的初音未来头像",
    is_circle: true,
  },
  {
    id: "avatar-009",
    title: "初音未来 · 经典画像",
    thumb_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/9eba6f017c95a3b3.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/9eba6f017c95a3b3.webp",
    origin_site: "https://www.3gbizhi.com/wallDM/907.html",
    keywords: "初音未来,VOCALOID,美少女,动漫,二次元头像",
    description: "经典动漫画像风初音未来头像",
    is_circle: false,
  },
  {
    id: "avatar-010",
    title: "初音未来 · 酷炫动漫",
    thumb_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/ca8417260b894ce6.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/ca8417260b894ce6.webp",
    origin_site: "https://www.3gbizhi.com/wallDM/1102.html",
    keywords: "初音未来,VOCALOID,酷炫,动漫少女,二次元头像",
    description: "酷炫动漫少女风初音未来头像",
    is_circle: true,
  },
  {
    id: "avatar-011",
    title: "初音未来 · 战士盔甲",
    thumb_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/69c02e4f38c9bd29.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/69c02e4f38c9bd29.webp",
    origin_site: "https://www.3gbizhi.com/wallDM/3567.html",
    keywords: "初音未来,VOCALOID,盔甲,战士,二次元头像",
    description: "穿戴战士盔甲的初音未来人物头像",
    is_circle: false,
  },
  {
    id: "avatar-012",
    title: "初音未来 · 像素风",
    thumb_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/684c554f25699262.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/684c554f25699262.webp",
    origin_site: "https://www.3gbizhi.com/wallDM/3377.html",
    keywords: "初音未来,VOCALOID,像素风,动漫,二次元头像",
    description: "像素风格的初音未来动漫女孩头像",
    is_circle: true,
  },
  {
    id: "avatar-013",
    title: "初音未来 · 经典美少女",
    thumb_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/1a9c5fdc3248c765.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/1a9c5fdc3248c765.webp",
    origin_site: "https://www.3gbizhi.com/wallDM/2005.html",
    keywords: "初音未来,VOCALOID,美少女,经典,二次元头像",
    description: "经典动漫美少女风初音未来头像",
    is_circle: true,
  },
  {
    id: "avatar-014",
    title: "初音未来 · 抱枕少女",
    thumb_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/c4f5555f6b490dfd.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/c4f5555f6b490dfd.webp",
    origin_site: "https://www.3gbizhi.com/wallDM/5848.html",
    keywords: "初音未来,VOCALOID,抱枕,插画,二次元头像",
    description: "抱着枕头的初音未来动漫插画头像",
    is_circle: false,
  },
  {
    id: "avatar-015",
    title: "初音未来 · 魔幻风",
    thumb_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/0cfe195ae6e8002c.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/0cfe195ae6e8002c.webp",
    origin_site: "https://www.3gbizhi.com/wallDM/2185.html",
    keywords: "初音未来,VOCALOID,魔幻,高清,二次元头像",
    description: "魔幻氛围的高清初音未来头像",
    is_circle: true,
  },
  {
    id: "avatar-016",
    title: "初音未来 · 星空梦幻",
    thumb_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/f9460f7d92bff1b0.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/f9460f7d92bff1b0.webp",
    origin_site: "https://www.3gbizhi.com/wallDM/3558.html",
    keywords: "初音未来,VOCALOID,星空,梦幻,二次元头像",
    description: "星空下梦幻卡通风的初音未来头像",
    is_circle: false,
  },
  {
    id: "avatar-017",
    title: "初音未来 · 个性魔力",
    thumb_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/5db7bb55c296983f.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/5db7bb55c296983f.webp",
    origin_site: "https://www.3gbizhi.com/wallDM/2231.html",
    keywords: "初音未来,VOCALOID,个性,魔力,二次元头像",
    description: "充满魔力的个性初音未来头像",
    is_circle: true,
  },
  {
    id: "avatar-018",
    title: "初音未来 · AI数字人",
    thumb_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/44e59a70407e1ef3.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/44e59a70407e1ef3.webp",
    origin_site: "https://www.3gbizhi.com/wallDM/6017.html",
    keywords: "初音未来,VOCALOID,AI,数字人,日系,二次元头像",
    description: "AI数字人主题日系初音未来插画头像",
    is_circle: false,
  },
  {
    id: "avatar-019",
    title: "初音未来 · 蓝发马尾",
    thumb_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/9aef4e8eb9ee6818.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/9aef4e8eb9ee6818.webp",
    origin_site: "https://www.3gbizhi.com/wallDM/5102.html",
    keywords: "初音未来,VOCALOID,蓝发,马尾辫,二次元头像",
    description: "蓝发马尾辫造型的初音未来高清头像",
    is_circle: true,
  },
  {
    id: "avatar-020",
    title: "初音未来 · 月下科幻",
    thumb_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/9b4e9a692f79f598.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/9b4e9a692f79f598.webp",
    origin_site: "https://www.3gbizhi.com/wallDM/4871.html",
    keywords: "初音未来,VOCALOID,科幻,月光,翅膀,二次元头像",
    description: "月光下科幻场景的梦幻初音未来头像",
    is_circle: false,
  },
  {
    id: "avatar-021",
    title: "初音未来 · 蝴蝶结大眼",
    thumb_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/29eeddeeea11d609.webp",
    origin_url: "https://cdn.jsdelivr.net/gh/mikuworldonline/img@main/c557/29eeddeeea11d609.webp",
    origin_site: "https://www.3gbizhi.com/wallDM/4189.html",
    keywords: "初音未来,VOCALOID,蝴蝶结,大眼,二次元头像",
    description: "戴蝴蝶结发带的大眼二次元初音头像",
    is_circle: true,
  },
];
