import type { Music } from "@/types";

// 音乐数据 - 初音未来经典名曲（真实可达的 YouTube 官方/本家来源）
// thumb_url 使用 YouTube 封面 (i.ytimg.com/vi/<id>/hqdefault.jpg)，origin_url 指向对应视频页
export const musicList: Music[] = [
  {
    id: "music-001",
    title: "World is Mine",
    artist: "ryo (supercell)",
    duration: "4:12",
    album: "supercell",
    thumb_url: "https://i.ytimg.com/vi/jhl5afLEKdo/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=jhl5afLEKdo",
    origin_site: "YouTube",
    keywords: "World is Mine,ワールドイズマイン,supercell,ryo,初音ミク,经典",
    description: "supercell（ryo）的代表作，讲述一位自认为是公主的少女的恋爱心事，是初音未来最具代表性的名曲之一。",
  },
  {
    id: "music-002",
    title: "千本桜",
    artist: "黒うさP (WhiteFlame)",
    duration: "4:05",
    album: "千本桜",
    thumb_url: "https://i.ytimg.com/vi/H27hOFa8qJY/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=H27hOFa8qJY",
    origin_site: "YouTube",
    keywords: "千本桜,千本樱,Senbonzakura,黒うさP,WhiteFlame,初音ミク,殿堂",
    description: "黒うさP 创作的和风摇滚名曲，2011 年发布后风靡全球，是 V 家殿堂级代表作。",
  },
  {
    id: "music-003",
    title: "メルト (Melt)",
    artist: "ryo (supercell)",
    duration: "4:01",
    album: "supercell",
    thumb_url: "https://i.ytimg.com/vi/ohzXX7iczrM/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=ohzXX7iczrM",
    origin_site: "YouTube",
    keywords: "メルト,Melt,ryo,supercell,初音ミク,爱情",
    description: "ryo 的早期代表作，清新动人的少女情歌，被誉为掀起 V 家热潮的奠基之作。",
  },
  {
    id: "music-004",
    title: "Tell Your World",
    artist: "kz (livetune)",
    duration: "4:00",
    album: "Re:Dial",
    thumb_url: "https://i.ytimg.com/vi/PqJNc9KVIZE/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=PqJNc9KVIZE",
    origin_site: "YouTube",
    keywords: "Tell Your World,livetune,kz,初音ミク,电音,Google Chrome",
    description: "Google Chrome 广告曲，livetune（kz）创作的明亮轻快的电子流行乐。",
  },
  {
    id: "music-005",
    title: "ハロ/ハワユ (Hello/How Are You)",
    artist: "ナノウ (ほえほえP)",
    duration: "3:39",
    album: "ハロ/ハワユ",
    thumb_url: "https://i.ytimg.com/vi/vNG6tKM7OWI/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=vNG6tKM7OWI",
    origin_site: "YouTube",
    keywords: "ハロ/ハワユ,Hello How Are You,ナノウ,ほえほえP,初音ミク,治愈",
    description: "ナノウ 创作的温柔治愈系名曲，描写宅居少女向世界打招呼的心情。",
  },
  {
    id: "music-006",
    title: "ロミオとシンデレラ (Romeo and Cinderella)",
    artist: "doriko",
    duration: "4:28",
    album: "Yume to Hazakura",
    thumb_url: "https://i.ytimg.com/vi/9HrOqmiEsN8/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=9HrOqmiEsN8",
    origin_site: "YouTube",
    keywords: "ロミオとシンデレラ,Romeo and Cinderella,doriko,初音ミク,童话,戏剧",
    description: "doriko 的代表作，将罗密欧与灰姑娘的意象融入少女恋曲，戏剧张力十足。",
  },
  {
    id: "music-007",
    title: "Just Be Friends",
    artist: "Dixie Flatline",
    duration: "4:28",
    album: "Just Be Friends",
    thumb_url: "https://i.ytimg.com/vi/esaV1kjzg_Q/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=esaV1kjzg_Q",
    origin_site: "YouTube",
    keywords: "Just Be Friends,JBF,Dixie Flatline,巡音ルカ,初音ミク,离别",
    description: "Dixie Flatline 的经典离别情歌，悲伤而克制的旋律打动无数听众。",
  },
  {
    id: "music-008",
    title: "ローリンガール (Rolling Girl)",
    artist: "wowaka",
    duration: "3:30",
    album: "アンハッピーリフレイン",
    thumb_url: "https://i.ytimg.com/vi/vnw8zURAxkU/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=vnw8zURAxkU",
    origin_site: "YouTube",
    keywords: "ローリンガール,Rolling Girl,wowaka,初音ミク,摇滚,殿堂",
    description: "wowaka 的高速摇滚名曲，急促的旋律与冲击性的歌词成为一代经典。",
  },
  {
    id: "music-009",
    title: "砂の惑星 (Dune)",
    artist: "ハチ (米津玄師)",
    duration: "3:38",
    album: "Magical Mirai 2017",
    thumb_url: "https://i.ytimg.com/vi/AS4q9yaWJkI/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=AS4q9yaWJkI",
    origin_site: "YouTube",
    keywords: "砂の惑星,Dune,ハチ,米津玄師,初音ミク,Magical Mirai",
    description: "ハチ（米津玄师）为初音未来十周年 Magical Mirai 2017 创作的主题曲。",
  },
  {
    id: "music-010",
    title: "マトリョシカ (Matryoshka)",
    artist: "ハチ (米津玄師)",
    duration: "3:24",
    album: "OFFICIAL ORANGE",
    thumb_url: "https://i.ytimg.com/vi/HOz-9FzIDf0/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=HOz-9FzIDf0",
    origin_site: "YouTube",
    keywords: "マトリョシカ,Matryoshka,ハチ,米津玄師,初音ミク,GUMI,殿堂",
    description: "ハチ 创作、初音未来与 GUMI 合唱的狂热名曲，独特的画风与节奏催生了无数二创。",
  },
  {
    id: "music-011",
    title: "テオ (Teo)",
    artist: "Omoi",
    duration: "3:34",
    album: "テオ",
    thumb_url: "https://i.ytimg.com/vi/bmkY2yc1K7Q/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=bmkY2yc1K7Q",
    origin_site: "YouTube",
    keywords: "テオ,Teo,Omoi,初音ミク,殿堂,热血",
    description: "Omoi 创作的高速热血名曲，澎湃的旋律与诗意的间奏歌词广受喜爱。",
  },
  {
    id: "music-012",
    title: "ゴーストルール (Ghost Rule)",
    artist: "DECO*27",
    duration: "3:30",
    album: "GHOST",
    thumb_url: "https://i.ytimg.com/vi/KushW6zvazM/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=KushW6zvazM",
    origin_site: "YouTube",
    keywords: "ゴーストルール,Ghost Rule,DECO*27,初音ミク,殿堂",
    description: "DECO*27 的代表名曲之一，凌厉的旋律与节奏感成为 V 家殿堂神话曲。",
  },
  {
    id: "music-013",
    title: "深海少女 (Deep Sea Girl)",
    artist: "ゆうゆ",
    duration: "3:52",
    album: "深海少女",
    thumb_url: "https://i.ytimg.com/vi/2CwBFr-Eoxg/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=2CwBFr-Eoxg",
    origin_site: "YouTube",
    keywords: "深海少女,Deep Sea Girl,ゆうゆ,初音ミク,治愈",
    description: "ゆうゆ 创作的梦幻名曲，描写生活在深海的少女，旋律柔美动人。",
  },
  {
    id: "music-014",
    title: "アンハッピーリフレイン (Unhappy Refrain)",
    artist: "wowaka",
    duration: "3:38",
    album: "アンハッピーリフレイン",
    thumb_url: "https://i.ytimg.com/vi/uMlv9VWAxko/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=uMlv9VWAxko",
    origin_site: "YouTube",
    keywords: "アンハッピーリフレイン,Unhappy Refrain,wowaka,初音ミク,殿堂",
    description: "wowaka 的高速摇滚名曲，飞快的咬字与紧凑的旋律是其标志性作品。",
  },
  {
    id: "music-015",
    title: "初音ミクの消失 (The Disappearance of Hatsune Miku)",
    artist: "cosMo@暴走P",
    duration: "4:06",
    album: "初音ミクの消失",
    thumb_url: "https://i.ytimg.com/vi/VWVtIg5cdDU/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=VWVtIg5cdDU",
    origin_site: "YouTube",
    keywords: "初音ミクの消失,The End of Hatsune Miku,cosMo,暴走P,初音ミク,高速,殿堂",
    description: "cosMo@暴走P 的超高速名曲，以惊人的咬字速度著称，是 V 家殿堂神话级作品。",
  },
  {
    id: "music-016",
    title: "ヒバナ (Hibana)",
    artist: "DECO*27",
    duration: "3:24",
    album: "GHOST",
    thumb_url: "https://i.ytimg.com/vi/hxSg2Ioz3LM/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=hxSg2Ioz3LM",
    origin_site: "YouTube",
    keywords: "ヒバナ,Hibana,火花,DECO*27,初音ミク,殿堂",
    description: "DECO*27 创作的人气名曲，节奏明快、旋律抓耳，YouTube 播放量过亿。",
  },
  {
    id: "music-017",
    title: "愛言葉III (Ai Kotoba III)",
    artist: "DECO*27",
    duration: "4:30",
    album: "愛言葉III",
    thumb_url: "https://i.ytimg.com/vi/WptXk39wiIQ/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=WptXk39wiIQ",
    origin_site: "YouTube",
    keywords: "愛言葉III,Ai Kotoba III,爱言葉,DECO*27,初音ミク,感恩",
    description: "DECO*27《爱言叶》系列第三作，初音未来对一路相伴之人表达爱与感谢的温柔之歌。",
  },
  {
    id: "music-018",
    title: "愛言葉II (Ai Kotoba II)",
    artist: "DECO*27",
    duration: "4:18",
    album: "愛言葉II",
    thumb_url: "https://i.ytimg.com/vi/KgpROErtiBY/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=KgpROErtiBY",
    origin_site: "YouTube",
    keywords: "愛言葉II,Ai Kotoba II,爱言葉,DECO*27,初音ミク,感恩",
    description: "DECO*27《爱言叶》系列第二作，延续对听众与初音未来之间羁绊的深情诉说。",
  },
  {
    id: "music-019",
    title: "エイリアンエイリアン (Alien Alien)",
    artist: "ナユタン星人",
    duration: "2:45",
    album: "ナユタン星からの物体X",
    thumb_url: "https://i.ytimg.com/vi/2t1NMRse6aI/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=2t1NMRse6aI",
    origin_site: "YouTube",
    keywords: "エイリアンエイリアン,Alien Alien,ナユタン星人,初音ミク,流行",
    description: "ナユタン星人 创作的太空主题人气曲，魔性旋律与外星设定深受年轻听众喜爱。",
  },
  {
    id: "music-020",
    title: "サンドリヨン (Cendrillon)",
    artist: "Dios/シグナルP",
    duration: "5:08",
    album: "サンドリヨン",
    thumb_url: "https://i.ytimg.com/vi/YE_S-OPHP8o/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=YE_S-OPHP8o",
    origin_site: "YouTube",
    keywords: "サンドリヨン,Cendrillon,シンデレラ,Dios,シグナルP,初音ミク,KAITO,对唱",
    description: "Dios/シグナルP 创作、初音未来与 KAITO 对唱的童话风名曲，灰姑娘故事的暗黑改编。",
  },
  {
    id: "music-021",
    title: "Packaged",
    artist: "kz (livetune)",
    duration: "3:53",
    album: "Re:package",
    thumb_url: "https://i.ytimg.com/vi/od-UmuK01vs/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=od-UmuK01vs",
    origin_site: "YouTube",
    keywords: "Packaged,livetune,kz,初音ミク,电音,出道曲",
    description: "livetune（kz）的出道名曲，清爽明亮的电子流行乐，奠定了其招牌曲风。",
  },
  {
    id: "music-022",
    title: "Sharing The World",
    artist: "BIGHEAD",
    duration: "3:53",
    album: "Sharing The World",
    thumb_url: "https://i.ytimg.com/vi/VJA-yPsul64/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=VJA-yPsul64",
    origin_site: "YouTube",
    keywords: "Sharing The World,BIGHEAD,初音ミク,MIKU EXPO,英文",
    description: "BIGHEAD 创作的 HATSUNE MIKU EXPO 2014 主题曲，面向全球听众的英文电音名曲。",
  },
  {
    id: "music-023",
    title: "DECORATOR",
    artist: "kz (livetune)",
    duration: "3:54",
    album: "Magical Mirai 2013",
    thumb_url: "https://i.ytimg.com/vi/zweVJrnE1uY/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=zweVJrnE1uY",
    origin_site: "YouTube",
    keywords: "DECORATOR,livetune,kz,初音ミク,Magical Mirai,电音",
    description: "livetune（kz）为初音未来演唱会 Magical Mirai 2013 创作的主题曲，华丽明快。",
  },
  {
    id: "music-024",
    title: "Gimme×Gimme",
    artist: "八王子P × Giga",
    duration: "2:50",
    album: "Gimme×Gimme",
    thumb_url: "https://i.ytimg.com/vi/ERo-sPa1a5g/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=ERo-sPa1a5g",
    origin_site: "YouTube",
    keywords: "Gimme Gimme,八王子P,Giga,初音ミク,鏡音リン,电音,人气",
    description: "八王子P 与 Giga 联手创作，初音未来与镜音铃合唱的时髦电音舞曲，极具人气。",
  },
  {
    id: "music-025",
    title: "Redial",
    artist: "kz (livetune)",
    duration: "3:51",
    album: "Re:Dial",
    thumb_url: "https://i.ytimg.com/vi/243vPl8HdVk/hqdefault.jpg",
    origin_url: "https://www.youtube.com/watch?v=243vPl8HdVk",
    origin_site: "YouTube",
    keywords: "Redial,livetune,kz,初音ミク,电音",
    description: "livetune（kz）的电子流行名曲，轻盈律动的节奏延续其标志性的清新曲风。",
  },
];
