import type { Music } from "@/types";

// 音乐示例数据 - 初音未来经典歌曲
export const musicList: Music[] = [
  {
    id: "music-001",
    title: "World is Mine",
    artist: "ryo (supercell)",
    duration: "4:32",
    album: "supercell",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/music/world_is_mine.webp",
    origin_url: "https://www.niconico.jp/video/5765040",
    origin_site: "Niconico",
    keywords: "World is Mine,world is mine,初音,甩葱歌,经典",
    description: "supercell的经典作品，初音未来代表性曲目之一",
  },
  {
    id: "music-002",
    title: "Tell Your World",
    artist: "kz (livetune)",
    duration: "4:15",
    album: "Re:_Mixed",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/music/tell_your_world.webp",
    origin_url: "https://www.niconico.jp/video/8330671",
    origin_site: "Niconico",
    keywords: "Tell Your World,livetune,初音,电音",
    description: "Google Chrome广告曲，轻快明亮的电子音乐风格",
  },
  {
    id: "music-003",
    title: "Promise",
    artist: "samfree",
    duration: "4:45",
    album: "Vocaloid",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/music/promise.webp",
    origin_url: "https://www.niconico.jp/video/11849592",
    origin_site: "Niconico",
    keywords: "Promise,初音,悲伤,抒情",
    description: "samfree的抒情曲，旋律优美动人",
  },
  {
    id: "music-004",
    title: "Just Be Friends",
    artist: "Dixie Flatline",
    duration: "4:28",
    album: "Vocaloid",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/music/just_be_friends.webp",
    origin_url: "https://www.niconico.jp/video/2891735",
    origin_site: "Niconico",
    keywords: "Just Be Friends,初音,悲伤,离别",
    description: "Dixie Flatline的代表曲目，悲伤而优美的旋律",
  },
  {
    id: "music-005",
    title: "Melt",
    artist: "ryo (supercell)",
    duration: "4:37",
    album: "supercell",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/music/melt.webp",
    origin_url: "https://www.niconico.jp/video/5081649",
    origin_site: "Niconico",
    keywords: "Melt,初音,supercell,爱情",
    description: "ryo的早期作品，初音的经典情歌",
  },
  {
    id: "music-006",
    title: "Romeo and Cinderella",
    artist: "doriko",
    duration: "4:52",
    album: "Vocaloid",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/music/romeo_cinderella.webp",
    origin_url: "https://www.niconico.jp/video/587610",
    origin_site: "Niconico",
    keywords: "Romeo and Cinderella,初音,童话,戏剧性",
    description: "doriko的代表作，讲述罗密欧与灰姑娘的童话故事",
  },
  {
    id: "music-007",
    title: "Levan Polkka",
    artist: "Otomania",
    duration: "2:04",
    album: "Vocaloid",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/music/levan_polka.webp",
    origin_url: "https://www.niconico.jp/video/139012",
    origin_site: "Niconico",
    keywords: "Levan Polkka,甩葱歌,初音,经典",
    description: "经典甩葱歌，红遍全球的初音代表性曲目",
  },
  {
    id: "music-008",
    title: "Rolling Girl",
    artist: "Wotamin",
    duration: "3:45",
    album: "Vocaloid",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/music/rolling_girl.webp",
    origin_url: "https://www.niconico.jp/video/4310339",
    origin_site: "Niconico",
    keywords: "Rolling Girl,初音,Wotamin,动感",
    description: "Wotamin的代表作，动感十足的摇滚风格",
  },
];
