import type { Sticker } from "@/types";

// 表情包示例数据 - 初音未来相关表情包
export const stickers: Sticker[] = [
  {
    id: "sticker-001",
    title: "初音萌萌表情包",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_01.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_01.webp",
      "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_01_02.webp",
      "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_01_03.webp",
    ],
    origin_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_01.webp",
    origin_site: "https://weibo.com",
    keywords: "初音未来,萌,可爱,表情包",
    description: "初音未来萌萌表情包合集",
    is_gif: false,
  },
  {
    id: "sticker-002",
    title: "初音搞怪GIF表情",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_02.gif",
    images: [
      "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_02.gif",
    ],
    origin_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_02.gif",
    origin_site: "https://pixiv.net",
    keywords: "初音未来,GIF,搞怪,动态表情",
    description: "初音未来搞怪GIF动态表情包",
    is_gif: true,
  },
  {
    id: "sticker-003",
    title: "初音VOCALOID表情包",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_03.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_03.webp",
      "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_03_02.webp",
    ],
    origin_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_03.webp",
    origin_site: "https://niconico.jp",
    keywords: "初音未来,VOCALOID,音乐,表情包",
    description: "VOCALOID主题初音表情包",
    is_gif: false,
  },
  {
    id: "sticker-004",
    title: "初音舞蹈GIF",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_04.gif",
    images: [
      "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_04.gif",
    ],
    origin_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_04.gif",
    origin_site: "https://pixiv.net",
    keywords: "初音未来,舞蹈,动感,GIF",
    description: "初音未来舞蹈动作GIF表情",
    is_gif: true,
  },
  {
    id: "sticker-005",
    title: "初音日常表情包",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_05.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_05.webp",
      "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_05_02.webp",
      "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_05_03.webp",
      "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_05_04.webp",
    ],
    origin_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_05.webp",
    origin_site: "https://weibo.com",
    keywords: "初音未来,日常,聊天,表情包",
    description: "适合日常聊天使用的初音表情包",
    is_gif: false,
  },
  {
    id: "sticker-006",
    title: "初音新年表情包",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_06.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_06.webp",
      "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_06_02.webp",
    ],
    origin_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_06.webp",
    origin_site: "https://pixiv.net",
    keywords: "初音未来,新年,祝福,节日表情",
    description: "新年主题初音表情包",
    is_gif: false,
  },
  {
    id: "sticker-007",
    title: "初音害羞表情包",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_07.webp",
    images: [
      "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_07.webp",
      "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_07_02.webp",
    ],
    origin_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_07.webp",
    origin_site: "https://pixiv.net",
    keywords: "初音未来,害羞,可爱,卖萌",
    description: "害羞风格的初音表情包",
    is_gif: false,
  },
  {
    id: "sticker-008",
    title: "初音吃东西GIF",
    thumb_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_08.gif",
    images: [
      "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_08.gif",
    ],
    origin_url: "https://cdn.jsdelivr.net/gh/0326/imgs@main/stickers/miku_sticker_08.gif",
    origin_site: "https://pixiv.net",
    keywords: "初音未来,吃东西,可爱,GIF",
    description: "初音吃东西的可爱GIF",
    is_gif: true,
  },
];
